name: general3
channels: !!python/tuple
- !!python/unicode 'defaults'
dependencies:
- cython=0.25.1=py35_0
- menpo::opencv3=3.1.0=py35_0
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - ale-python-interface==0.0.1
  - atari-py==0.0.18
  - autoflake==0.6.6
  - autopep8==1.2.4
  - box2d-py==2.3.1
  - cached-property==1.3.0
  - chainer==1.18.0
  - filelock==2.0.7
  - flake8==3.2.1
  - h5py==2.6.0
  - imageio==1.6
  - keras==1.1.2
  - mccabe==0.5.2
  - mujoco-py==0.5.6
  - nose==1.3.7
  - pachi-py==0.0.21
  - pep8==1.7.0
  - pillow==3.4.2
  - protobuf==3.1.0.post1
  - pycodestyle==2.2.0
  - pyflakes==1.3.0
  - pyglet==1.2.4
  - pyopengl==3.1.0
  - pyyaml==3.12
  - requests==2.12.1
  - scipy==0.18.1
  - six==1.10.0
  - theano==0.8.2
